- name: make backend dir
  become: yes
  file:
    path: /home/ubuntu/backend
    state: directory
- name: "Unarchive files and move to ec2"
  become: yes
  unarchive:
    src: ~/project/artifact.tar.gz
    dest: /home/ubuntu/backend
- name: Install dependencies
  become: yes
  shell: |
    cd /home/ubuntu/backend
    npm install
- name: "install pm2"
  become: yes
  npm:
    name: pm2
    global: yes
    production: yes
    state: present
- name: start erver
  shell: |
    pm2 stop default
    pm2 start npm -- start